stages:
  - build
  - test
  - deploy

image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

build:
  stage: build
  script: 
  - bundle install
  - bundle exec jekyll build -d build
  artifacts:
    expire_in: 1 month
    paths:
      - build

test:
  stage: test
  image: registry.gitlab.com/elderlydoofus/joshuadavidthomas/linkchecker:latest
  script:
  - linkchecker build
  artifacts:
    paths:
    - build

pages:
  stage: deploy
  script:
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master