stages:
  - build
  - test
  - deploy

image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

build:
  stage: build
  script: 
  - bundle install
  - bundle exec jekyll build -d build
  - mv _site test
  artifacts:
    expire_in: 1 month
    paths:
      - test

test:
  stage: test
  image: linkchecker:latest
  script:
  - webfsd -p 4000 -f index.html
  - linkchecker http://localhost:4000/test/
  artifacts:
    paths:
    - test

pages:
  stage: deploy
  dependencies:
    - test
  script:
  - mv test public
  artifacts:
    paths:
    - public
  only:
  - master