language: ruby
branches:
  only:
  - master
rvm:
- 2.2.7
before_script:
- chmod +x cibuild.sh
script: "./cibuild.sh"
exclude:
- vendor
sudo: false
notifications:
  pushover:
    api_key:
      secure: EiAX0GN2r1EUDE/cvJql8AyeG5W8ZN2NgFher/SIKfnTzDog2MUZmW+oraLFi7QwLT2yyTzBNrbENX3YQLmeUHEyryO0p1CcVqOcmMI7fmuNqN+hDolkOlazuVHtnPGmFWIgLOoubMtZb0SrayNj4kiXtaiZkFdMHFoSs0n8ZJw1RUNdkrrrCK1/T6NIp2RDjz51MYeA8LEvSKAkaP8eLy6vbVBL6PyX/0MHV+RrSPjnMij/zfbEZygwkwp162COEoqGHjNwmYJzzkrYbV0G4JRa8zgFqNtY956Z630AOxtz9LchsVuxkPnlroYpDFYNSYY8qZZL1p0LiA2Aef8VfyyDKlWnlKygM/mPrNlRdXy/m62Jo3y8hmjCxsCNf/1OGj4ZXEWCzgqlgh+6jB1r2j2PRdRwMHoHNwlcIXLpvdKanIkraEbqlf6bz47t9oOCJHJ9nCFN8zkQOo58x8JmhYnsCtJJ0vaXeZsOobviYUPIe8DCAynIthui0SY92scFXu7weqR8RtaPjS6lvX3wP3sVMdHEZtAOqyybwVOeuY+I3KsuJwz3Q1UkyZy6qdDWxAn3nfg8VTBx0QuYL02UlmUI2K15/s9bq1EYiVrg1YHRTMumbtY4IK5oEuLzeofI9Zo15M6e6OElJaaEklWp6QhC+kQ9b+C8VHMQRPAbivI=
    users:
      secure: lK+3YImEeSc+ukkcNy4nPvqtJjbc7bOvVDiexx+9DXnn9MSazLIpee8qa5CkY2FergHrOvpjFZJ82G0a190dYvzGACAcYb6CVcDaLI7ZSKfdz2ewXeNJVvXOygeVDemZ682JzyZGew4FRM96h9q9eA/6ChK1gxsFz+mF/M0ncPM2HsF0OjObIFZkFqPKNgnk8SNs9VmSXHuYON49xdjKFdVmrBgqquyK59aqlB55SntwZsaxlz98g5Y+CZYnApLCUXw1giC8YPW3kVPkFMdzX05ZnEtnX+wW4i1/+AQ5SLfmoZvfe/+QwaiU6QxJLOQ7gXXF5A4RW77zRbQc4qmTf4sPfcc/LvduwDauVE+ptbgXKoiPRlFiBzD/pb82fAtH4fqNebQ8Zxwh/Rdq1Jv1NOMjx1zjBxL0lL0WsJVrbDU9rlDNcDnOHsxKPDl4ox1pQ3Dz6nJX9+kKs+Yt6QbDvBHcCWpcw13y0qtB7SGAk0xInfVx1VlJux/+GOxn2+f3zHl7Di79aRSeKEcIpGvxX6zGlFWVVGkkTeUrejkzpg2bGj3DDRLxjDPX9q1amw7J8fbxkW61KlJRlSnOsLDHQbVFVPHpCsRnSLLLvWXsKVcec7UKPUWlTWoxNsOHHLWTGsdPKqFbsSxFynkIUmrXm6rNWvu9zk4KSnEHNfQRY7o=
