title: Joshua David Thomas
email: contact@joshuadavidthomas.com
description: >- # this means to ignore newlines until "baseurl:"
  Homepage for Joshua David Thomas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.joshuadavidthomas.com" # the base hostname & protocol for your site, e.g. http://example.com

# social
twitter_username: jimmyjosh
github_username:  joshuadavidthomas

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
