version: "3"

x-app: &default-app
  build:
    context: .
    dockerfile: Dockerfile
    target: app
  env_file: .env
  init: true
  user: "${UID:-1000}:${GID:-1000}"
  volumes:
    - .:/app:cached
  working_dir: /app

services:
  app:
    <<: *default-app
    command: python manage.py runserver 0.0.0.0:8000 --skip-checks
    ports:
      - "${DJANGO_PORT:-8000}:8000"

  node:
    <<: *default-app
    build:
      target: tailwind
    command:
      - bash
      - -c
      - |
        npm install
        npm run dev
    depends_on: []
    ports:
      - "5173:5173"

  tailwind:
    <<: *default-app
    build:
      target: tailwind
    command: python manage.py tailwind --skip-checks watch
    tty: true
