# fly.toml app configuration file generated for joshthomasdev on 2023-08-31T16:59:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "joshthomasdev"
primary_region = "atl"
console_command = "/app/manage.py shell_plus"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "python manage.py migrate"

[env]
  ALLOWED_HOSTS = "joshthomasdev.fly.dev"
  DEBUG = "False"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static/"
