[tool.bumpver]
commit = true
commit_message = ":bookmark: bump version {old_version} -> {new_version}"
current_version = "2024.4.7"
push = false  # set to false for CI
tag = true
version_pattern = "YYYY.MM.INC1"

[tool.bumpver.file_patterns]
"config/__init__.py" = ['__version__ = "{version}"']
"tests/test_version.py" = ['assert __version__ == "{version}"']

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "if DEBUG:",
  "if not DEBUG:",
  "if settings.DEBUG:",
  "if TYPE_CHECKING:",
  'def __str__\(self\)\s?\-?\>?\s?\w*\:',
]

[tool.coverage.run]
omit = ["*/migrations/*"]
source = ["blog", "config", "core", "flyio", "users"]

[tool.django-stubs]
django_settings_module = "config.settings"

[tool.djlint]
blank_line_after_tag = "load,extends,endblock,endpartialdef"
blank_line_before_tag = "block,partialdef"
custom_blocks = "partialdef"
ignore = "H031"                                              # Don't require `meta` tag keywords
indent = 2
profile = "django"

[tool.mypy]
check_untyped_defs = true
files = ["blog", "config", "core", "flyio", "users"]
no_implicit_optional = true
plugins = ["mypy_django_plugin.main"]
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
ignore_errors = true
module = ["*.migrations.*"]

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
  "allauth.*",
  "debug_toolbar.*",
  "django_twc_toolbox.*", # TODO: remove when I add `py.typed` to this package
  "djclick.*",
  "gunicorn.*",
  "health_check.*",
  "neapolitan.*",
  "qrcode.*",
  "simple_history.*",
]

[tool.mypy_django_plugin]
ignore_missing_model_attributes = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
addopts = "--reuse-db -n auto --dist loadfile"
norecursedirs = ".* bin build dist *.egg htmlcov logs node_modules templates venv"
python_files = "tests.py test_*.py *_tests.py"

[tool.ruff]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".github",
  ".hg",
  ".mypy_cache",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "migrations",
  "node_modules",
  "static",
  "venv",
]
# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "I"]
ignore = ["E501", "E741"]                     # temporary
indent-width = 4
# Same as Black.
line-length = 88
per-file-ignores = {}
select = [
  "B", # flake8-bugbear
  "E", # Pycodestyle
  "F", # Pyflakes
  "I", # isort
]
# Assume Python 3.12
target-version = "py312"
unfixable = []

[tool.ruff.format]
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
# Like Black, use double quotes for strings.
quote-style = "double"

[tool.ruff.isort]
force-single-line = true
known-first-party = ["blog", "config", "core", "flyio", "users"]
required-imports = ["from __future__ import annotations"]
