name: Deploy

on:
  push:
    tags:
      - "^20[0-9]+.[0-9]+$"
    branches:
      - main
  workflow_dispatch:

concurrency: production

env:
  UV_VERSION: "0.4.x"

jobs:
  bumpver:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.bumpver.outputs.current_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: Configure git to push
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "Automated Publisher"

      - name: Bump Version
        id: bumpver
        run: |
          uv run --with bumpver bumpver update
          eval $(uv run --with bumpver bumpver show --env)
          echo "{current_version}=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Regenerate uv.lock
        run: |
          uv sync
          if git diff --quiet uv.lock; then
            echo "No changes to uv.lock"
          else
            git add uv.lock
            git commit -m "Update uv.lock"
          fi

      - name: Push Release Build to GitHub
        run: |
          git push

  deploy:
    runs-on: ubuntu-latest
    needs: bumpver
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          FLY_API_TOKEN: "op://GitHub Actions/joshthomas.dev/FLY_API_TOKEN"

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only

  sentry:
    runs-on: ubuntu-latest
    needs: bumpver
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SENTRY_AUTH_TOKEN: "op://GitHub Actions/sentry/RELEASE_TOKEN"

      - name: Create Sentry release
        uses: getsentry/action-release@v1.7.0
        env:
          SENTRY_ORG: "dunbrook-web"
          SENTRY_PROJECT: "joshthomasdev"
        with:
          environment: production
          version: ${{ needs.bumpver.outputs.current_version }}
