name: Test

on:
  pull_request:
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}

env:
  CI: true
  FORCE_COLOR: 1
  NODE_VERSION: "20"
  UV_VERSION: "0.4.x"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v4
        id: cache-npm
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          uv sync --locked --dev
          npm install

      - name: Install system packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            build-essential
          playwright install --with-deps

      - name: Run migrations
        run: |
          python -m manage migrate --skip-checks

      - name: Build staticfiles
        run: |
          python -m manage tailwind --skip-checks build
          python -m manage collectstatic --no-input --skip-checks --no-default-ignore

      # https://hynek.me/articles/ditch-codecov-python/
      - name: Run tests
        run: |
          uv run pytest --durations 10 -n auto --dist loadfile --cov --cov-report= --cov-config=pyproject.toml
          uv run coverage html --skip-covered --skip-empty
          uv run coverage report | sed 's/^/    /' >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.run_id }}
          path: htmlcov

  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: Install dependencies
        run: |
          uv sync --locked --dev

      - name: Run mypy
        env:
          DATABASE_URL: sqlite:///db.sqlite3
        run: |
          uv run mypy

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: Install dependencies
        run: |
          uv sync --locked --dev

      - name: Run deployment checks
        env:
          DEBUG: False
          DATABASE_URL: sqlite:///db.sqlite3
        run: |
          uv run manage.py check --deploy
